OPERATIVE_FRAMEWORK_VERSION = "HD 1.0"

MONGODB_USER = "operative"
MONGODB_PASS = "operative"
MONGODB_PORT = 27017
MONGODB_HOST = "localhost"

BREACH_LIMIT = 300

BACKEND_PORT = "5000"
FRONTEND_PORT = "3000"
